// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlugBusSchedule.Models;

namespace SlugBusSchedule.Migrations
{
    [DbContext(typeof(SlugContext))]
    [Migration("20190714024005_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SlugBusSchedule.Models.Schedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Base");

                    b.Property<string>("BookStore");

                    b.Property<string>("BusNumber");

                    b.Property<string>("CrownMerill");

                    b.Property<string>("EastRemote");

                    b.Property<string>("Kresge");

                    b.Property<string>("NineTen");

                    b.Property<string>("Oakes");

                    b.Property<string>("PorterRachelCarson");

                    b.Property<string>("ScienceHill");

                    b.Property<string>("Street");

                    b.Property<string>("Village");

                    b.HasKey("ID");

                    b.ToTable("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
